### ISSUE TITLE
Can not build the project on linux

### ISSUE THREAD

**Issue by Prunkles** [Shmew/Fable.SignalR#3]
## Description

When I execute `fake build` it throws an error:
```
Script reported an error:
-> BuildFailedException: Target 'YarnInstall' failed.
-> One or more errors occurred. (Start of process '/home/prunkles/Develop/repos/Shmew/Fable.SignalR/packages/tooling/Yarnpkg.Yarn/content/bin/yarn.cmd' failed.)
-> Start of process '/home/prunkles/Develop/repos/Shmew/Fable.SignalR/packages/tooling/Yarnpkg.Yarn/content/bin/yarn.cmd' failed.
-> Win32Exception: Permission denied
```

## Steps to reproduce

1. Be on Linux
2. Execute `fake build`

## Expected behavior

Successful compilation of the project.

## Additional context

OS: Manjaro Linux x86_64
Kernel: 4.19.126-1-MANJARO

**Comment by Shmew** [comment]
It should be fixed now, feel free to re-open if that's not the case.

**Comment by Prunkles** [comment]
Unfortunately, I still can't.
Now an error occurs during the 'Build' target:
```
/usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error : The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. [/home/prunkles/Develop/repos/Shmew/Fable.SignalR/src/Fable.SignalR.Saturn/Fable.SignalR.Saturn.fsproj]
```
I see that FAKE is trying to use Mono to build, but it requires .NET Core.

Of course, I have all the necessary SDKs:
```
$ dotnet --info
...
.NET Core SDKs installed:
  2.1.807 [/usr/share/dotnet/sdk]
  2.2.207 [/usr/share/dotnet/sdk]
  3.0.103 [/usr/share/dotnet/sdk]
  3.1.103 [/usr/share/dotnet/sdk]
```

Full console output with `FAKE_DETAILED_ERRORS=true` ([click](https://github.com/Shmew/Fable.SignalR/files/4909748/fake-out.log))

**Comment by Prunkles** [comment]
I would also like to report an error related to the `paket.lock` file.
When I try to build immediately after cloning the repository, I catch another error:
```
There was a problem while setting up the environment:
-> Error during parsing of '/home/prunkles/Develop/repos/Shmew/Fable.SignalR/paket.lock'.
-> invalid parameter 'netcoreapp5.0' after >= or < in '< netcoreapp5.0) (>= netstandard2.0) (< xamarinios) (< xamarinmac)) (>= netcoreapp2.0)'
```
Deleting the lock file fixes this, but I'm not sure that `netcoreapp5.0` is really necessary.

Also, perhaps the problem above is related to these actions.

**Comment by Shmew** [comment]
I'm not really sure what's going on here, but you could try updating to 3.1.301. Outside of that, I'd welcome a PR that properly enables you to build the project.
